name: Build Arch Package

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux:base-devel

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          pacman -Sy --noconfirm
          pacman -S --noconfirm sudo base-devel git

      - name: Create builder
        run: |
          useradd -m builder
          echo "builder ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
          chown -R builder:builder .

      - name: Build package
        run: |
          sudo -u builder makepkg -sf --noconfirm

      - name: Upload package
        uses: actions/upload-artifact@v4
        with:
          name: arch-package
          path: "*.pkg.tar.zst"
